import {
  AirVent,
  Baby,
  Banknote,
  Bath,
  Building2,
  Car,
  Clock,
  Coffee,
  ConciergeBell,
  CupSoda,
  Droplets,
  Dumbbell,
  Flame,
  Heart,
  Key,
  LampDesk,
  Luggage,
  Map,
  Plane,
  Refrigerator,
  ShieldCheck,
  Shirt,
  ShowerHead,
  Sparkles,
  Star,
  Sunset,
  Trees,
  Tv,
  Utensils,
  UtensilsCrossed,
  Vault,
  Waves,
  Wifi,
  Wind,
  DoorOpen,
  type LucideIcon,
} from 'lucide-react'
import type { Amenity, ServiceIcon } from '../content/types'

export const AMENITY_ICONS: Record<Amenity, LucideIcon> = {
  wifi: Wifi,
  breakfast: UtensilsCrossed,
  ac: AirVent,
  tv: Tv,
  fridge: Refrigerator,
  kettle: CupSoda,
  safe: Vault,
  wardrobe: Shirt,
  shower: ShowerHead,
  toiletries: Sparkles,
  hairdryer: Wind,
  desk: LampDesk,
  balcony: DoorOpen,
  cityView: Building2,
  roomService: ConciergeBell,
}

export const SERVICE_ICON_COMPONENTS: Record<ServiceIcon, LucideIcon> = {
  waves: Waves,
  flame: Flame,
  droplets: Droplets,
  utensils: Utensils,
  coffee: Coffee,
  sunset: Sunset,
  concierge: ConciergeBell,
  clock: Clock,
  currency: Banknote,
  wifi: Wifi,
  trees: Trees,
  car: Car,
  plane: Plane,
  shirt: Shirt,
  baby: Baby,
  dumbbell: Dumbbell,
  bath: Bath,
  key: Key,
  map: Map,
  luggage: Luggage,
  shield: ShieldCheck,
  heart: Heart,
  star: Star,
  sparkles: Sparkles,
}
